- common/changes/@itwin/service-authorization/update-token-prefix_2022-02-08-03-03.json
- packages/service/src/introspection/IntrospectionClient.ts
- packages/service/src/test/Introspection.test.ts
The current handling resulted in a difficult to parse error when attempting to get the `substr` of a string with length of 0. Updated the handling to use split instead of `substr`.
> Update how the token prefix is removed

- common/changes/@itwin/node-cli-authorization/better-token-store-key_2022-04-27-15-05.json
- packages/node-cli/package.json
- packages/node-cli/src/Client.ts
Incorporate issuerUrl into TokenStore key to avoid conflicts between credentials that share a clientId but were generated from different issuing authorities. This is a common problem for Bentley when testing between QA and PROD.
Also shortened the "iTwinJs" boilerplate to make the entries more readable in Credential Manager, etc.
> Include issuerUrl in TokenStore key

- common/changes/@itwin/electron-authorization/gytis-support-for-Electron-22_2022-12-05-15-34.json
- common/config/rush/pnpm-lock.yaml
- packages/electron/package.json
- Add _Electron 22_ as supported Electron version.
- Increase version of Electron dev dependency to `^22.0.0`.
[Electron breaking changes.](https://github.com/electron/electron/blob/main/docs/breaking-changes.md#planned-breaking-api-changes-220)
We don't use any of removed or changed APIs.
Electron versions 18 - 21 were skipped due to bug that affects _@itwin/core-electron_ package (detailed description in https://github.com/iTwin/itwinjs-core/pull/4640).
> Add support for Electron 22

- common/changes/@itwin/browser-authorization/mindaugas-upgrade-jsonwebtoken_2022-12-23-13-41.json
- common/changes/@itwin/electron-authorization/mindaugas-upgrade-jsonwebtoken_2022-12-23-13-41.json
- common/changes/@itwin/oidc-signin-tool/mindaugas-upgrade-jsonwebtoken_2022-12-23-13-41.json
- common/changes/@itwin/service-authorization/mindaugas-upgrade-jsonwebtoken_2022-12-23-13-41.json
- common/config/rush/pnpm-lock.yaml
- packages/browser/package.json
- packages/electron/package.json
- packages/oidc-signin-tool/package.json
- packages/service/package.json
- packages/service/src/test/Introspection.test.ts
`jsonwebtoken` (<= 8.5.1) has insecure input validation in jwt.verify function - https://github.com/advisories/GHSA-27h2-hvpr-p74q .
Upgraded `jsonwebtoken` to 9.0.0.
Also upgraded `sinon` and changed the tests a bit, because it is no longer possible to mock `decode`.
Fixes #94
> Upgraded jsonwebtoken

- common/changes/@itwin/electron-authorization/gytis-change-Electron-support-range_2023-02-09-10-56.json
- common/config/rush/pnpm-lock.yaml
- packages/electron/package.json
- Dropped Electron versions:
- Electron 14, 15, 16, 17 - reached end-of-life.
- Electron 22 - uses Node 16, which we want to drop.
- Added support for Electron 23. No changes are required since none of the [breaking changes](https://github.com/electron/electron/blob/main/docs/breaking-changes.md#planned-breaking-api-changes-230) should affect us.
> Start supporting Electron 23, drop older Electron versions

- common/changes/@itwin/browser-authorization/bdp-fix-oidc-ts-state-redirect_2023-02-28-15-52.json
- packages/browser/src/Client.ts
Missed in the upgrade to `oidc-client-ts` - user-defined state must be passed as a state property to `signinRedirect` rather than as the first argument itself.
> correctly specify user redirect state

- common/changes/@itwin/browser-authorization/bdp-signin-tool-use-puppeteer-93_2023-03-10-16-55.json
- common/changes/@itwin/oidc-signin-tool/bdp-signin-tool-use-puppeteer-93_2023-03-10-16-55.json
- common/changes/@itwin/oidc-signin-tool/bdp-signin-tool-use-puppeteer-93_2023-03-10-17-24.json
- common/changes/@itwin/oidc-signin-tool/bdp-signin-tool-use-puppeteer-93_2023-03-10-17-26.json
- common/config/azure-pipelines/integration-test.yaml
- common/config/rush/pnpm-lock.yaml
- packages/browser/package.json
- packages/oidc-signin-tool/README.md
- packages/oidc-signin-tool/package.json
- packages/oidc-signin-tool/playwright.config.ts
- packages/oidc-signin-tool/src/TestBrowserAuthorizationClient.ts
- packages/oidc-signin-tool/src/TestSelectors.ts
- packages/oidc-signin-tool/src/TestUsers.ts
- packages/oidc-signin-tool/src/test-integration/basic.test.ts
- packages/oidc-signin-tool/src/test-integration/loadConfig.ts
- packages/oidc-signin-tool/src/test/TestUtility.test.ts
- packages/oidc-signin-tool/tsconfig.json
Replaces the use of puppeteer with playwright for the oidc-signin-tool:
- No need to mock the response to the callback url, instead grab the url with code and state by waiting for the redirect request.
- Replace puppeteer syntax and clunky waits
- Add option to simulate slow network condition when launching browsers to ensure waits work as expected.
#93
> oidc-signin-tool: replace puppeteer with playwright

- common/changes/@itwin/electron-authorization/gytis-Electron-24-support_2023-04-12-14-49.json
- common/config/rush/pnpm-lock.yaml
- packages/electron/package.json
- Extend supported Electron versions with Electron 24.
- Increase Electron dev dependency version to `^24.0.0`.
No code changes are required since we don't use [changed API](https://github.com/electron/electron/blob/main/docs/breaking-changes.md#planned-breaking-api-changes-240).
> Add support for Electron 24

- common/changes/@itwin/browser-authorization/bdp-configless-callback_2023-04-13-14-43.json
- packages/browser/README.md
- packages/browser/playwright.config.ts
- packages/browser/src/Client.ts
- packages/browser/src/integration-tests/helpers/TestHelper.ts
- packages/browser/src/integration-tests/integration.test.ts
- packages/browser/src/integration-tests/test-app/index.ts
- packages/browser/src/integration-tests/types.ts
- packages/browser/src/types.ts
After recent changes, we required an instance of a fully configured `BrowserAuthorizationClient` to call `handleSigninCallback()`. This change adds a new static method which automatically pulls client configuration from local storage. Conveniently, OIDC stores the config using the returned `state` nonce as a key, so we use that to ensure the correct configuration is being selected (consider the case of multiple clients, or possibly stale clients).
> add static method for configless sign in callback

- common/changes/@itwin/browser-authorization/bdp-add-documentation_2023-04-07-20-54.json
- common/changes/@itwin/browser-authorization/bdp-bump-itwin-deps-types_2023-05-02-16-44.json
- common/changes/@itwin/browser-authorization/core-range_2023-04-24-15-34.json
- common/changes/@itwin/browser-authorization/publish-1681508677055_2023-04-17-18-46.json
- common/changes/@itwin/oidc-signin-tool/bdp-102-consolidate-browser-auth-callback-handler_2023-03-20-17-32.json
- common/changes/@itwin/oidc-signin-tool/bdp-add-documentation_2023-04-07-20-54.json
- common/changes/@itwin/oidc-signin-tool/bdp-bump-itwin-deps-types_2023-05-02-16-44.json
- common/changes/@itwin/oidc-signin-tool/core-range_2023-04-24-15-34.json
- common/changes/@itwin/oidc-signin-tool/publish-1678929819302_2023-03-16-14-30.json
- common/config/rush/pnpm-lock.yaml
- packages/browser/CHANGELOG.json
- packages/browser/CHANGELOG.md
- packages/browser/package.json
- packages/oidc-signin-tool/CHANGELOG.json
- packages/oidc-signin-tool/CHANGELOG.md
- packages/oidc-signin-tool/package.json
- rush.json
In trying to understand why the latest run did not publish the intended packages, I accidentally triggered a version bump with merges from my local machine. This reverts that sloppiness.
> Revert dfbe5a6 d0bdd3a (premature rush version)

- common/changes/@itwin/oidc-signin-tool/no-fetch_2023-06-02-09-03.json
- packages/oidc-signin-tool/package.json
- packages/oidc-signin-tool/src/TestBrowserAuthorizationClient.ts
Without this metadata, the client uses `fetch` to get issuer metadata, which is not always available (especially in older Node.js versions)
> pass metadata to oidc-client-ts

- common/config/azure-pipelines/ci.yml
No reason to validate the docs at that point in the publishing workflow, at least not in that manner.
> Fix publish pipeline attempt 2

- common/changes/@itwin/browser-authorization/add-logout-url-note-readme_2023-08-02-20-23.json
- packages/browser/README.md
Cannot use `/logout` as postSignoutRedirectUri when redirecting to http. Added guidance in readme.
> add info about postSignoutRedirectUri quirk to browser-auth readme

- change/@itwin-electron-authorization-b40a7a08-594d-4aee-8cfa-4bc079627241.json
- packages/electron/package.json
- pnpm-lock.yaml
- Extend supported Electron version range with Electron 27.
- Increase Electron dev dependency version to `^27.0.0`.
No code changes required since auth client doesn't use [APIs changed in 27](https://github.com/electron/electron/blob/main/docs/breaking-changes.md#planned-breaking-api-changes-270).
> Add support for Electron 27

- change/@itwin-oidc-signin-tool-ca6fd177-8f76-4fe4-afb8-ea94ece5d83c.json
- packages/oidc-signin-tool/src/SignInAutomation.ts
- packages/oidc-signin-tool/src/test-integration/basic.test.ts
Using `locator.fill` is [the recommended way](https://playwright.dev/docs/input#text-input) to fill out input, and [`Page.type` is now deprecated](https://playwright.dev/docs/api/class-page#page-type).
I made these changes using `pnpm patch` for my Electron application, and I *think* it will close https://github.com/iTwin/auth-clients/issues/224 but I can't be sure because the issue is flaky and doesn't happen frequently.
> Replace playwright `type` calls with `fill`

- change/@itwin-electron-authorization-cb30a53e-3752-4c76-829e-b7017135452b.json
- packages/electron/src/main/Client.ts
- packages/electron/src/renderer/Client.ts
tldr: Resolve the `ElectronRendererAuthorization.signIn()` promise when sign-in has fully completed, and reject on errors. Closes https://github.com/iTwin/auth-clients/issues/226.
Previously, some sign-in errors (e.g., an internal server error on the token issuer server) were uncaught by `ElectronRendererMain`, and there wasn't a way for consumers of this package to catch it. The frontend who initiated the sign-in was left waiting for `onAccessTokenChanged` forever. Now, we resolve the promise when sign in has actually fully completed or reject the promise if there was an error during sign in, so that the frontend can show an error message.
Technically the API is the same, the types are the same, but the usage could vary slightly.
```jsx
const onSignInClick = async (): Promise<void> => { …
```
> Resolve `signIn` promise when sign in has completed

- change/@itwin-electron-authorization-82609d51-3709-4e72-a06c-81f5102e39cc.json
- change/@itwin-node-cli-authorization-85c83eb7-603e-450c-90d1-06fe62b6b77c.json
- packages/electron/.npmignore
- packages/node-cli/.npmignore
Static loopback pages needed to be published to npm, they were ignored by the `.npmignore` file, resulting in a runtime `ENOENT: no such file or directory`
> Publish static loopback pages

- change/@itwin-electron-authorization-3fc394c2-f7aa-40d6-bd98-6d5a9ef44b14.json
- packages/electron/src/main/TokenStore.ts
Utility process in electron doesn't have electron context and it has to be polyfilled with async functions
> Anticipate safeStorage to be polyfilled with async functions

- change/@itwin-electron-authorization-42c4719f-cdb4-4366-a501-63704e26e476.json
- packages/electron/src/main/TokenStore.ts
- packages/electron/src/test/MainAuthorizationClient.test.ts
Packaged app cannot decrypt not packaged apps token and vice versa. In case tokenStorePath is the same for both types of app, we need to handle decryptRefreshToken failure
> Handle decryptRefreshToken failure

- change/@itwin-oidc-signin-tool-72d420f2-1d03-410b-bb97-a96a43c6e8c5.json
- packages/oidc-signin-tool/src/SignInAutomation.ts
In EU the cookie consent banner is obscuring the "Accept" button and must be dismissed before proceeding.t
> Add EU cookie consent banner handling to OIDC sign in

- change/@itwin-oidc-signin-tool-00322da7-937f-4373-8299-e57836f62525.json
- packages/oidc-signin-tool/src/SignInAutomation.ts
Previous commit would make the tests time out because it was waiting for an element that does not exist outside of EU.
The `page.locator` is a safe alternative for optional elements.
> Fix EU cookie consent banner selector

- change/@itwin-electron-authorization-ecff8084-b15a-47e7-8a0f-138ea86b3580.json
- packages/electron/src/common/constants.ts
- packages/electron/src/main/Client.ts
- packages/electron/src/renderer/Client.ts
Unify expiry buffer accross electron auth clients
- added ability to set expiryBuffer for ElectronRendererAuthorization, defaulting to 10 min
- added defaultExpiryBufferInSeconds to be reused in both electron auth clients
- added ElectronRendererAuthorization._tokenRequest to be returned instead of Promise.reject() to short-circuit any recursive use of ElectronRendererAuthorization.getAccessToken
Fixes #232
> Unify expiry buffer accross electron auth clients

- change/@itwin-electron-authorization-c23454e0-2ce1-4ca5-b18b-513b6969c59a.json
- packages/electron/package.json
When using `export` and subpaths, to fully support CJS and ESM, we need each subpath to contain `import` and `require`.
Previously, `./Renderer` didn't support CJS, because it didn't have a `require` field. This would cause problems in packages, like `itwinjs/core` `core-full-stack-tests`, that consumes both Main and Renderer, but outputs CJS files. At build time, this wouldn't be caught, but during runtime, it would throw a `PACKAGE_PATH_NOT_SUPPORTED`, because when it tried to use the Renderer subpath, it couldn't find a valid CJS path.
Vice versa, with `./Main` in ESM outputted files.
This issue is fixed by adding both `import` and `require` and their valid values to each subpath.
> Add missing support for subpaths

- pnpm-lock.yaml
```
┌─────────────────────┬────────────────────────────────────────────────────────┐
│ high                │ body-parser vulnerable to denial of service when url   │
│                     │ encoding is enabled                                    │
├─────────────────────┼────────────────────────────────────────────────────────┤
│ Package             │ body-parser                                            │
├─────────────────────┼────────────────────────────────────────────────────────┤
│ Vulnerable versions │ <1.20.3                                                │
├─────────────────────┼────────────────────────────────────────────────────────┤
│ Patched versions    │ >=1.20.3                                               │
├─────────────────────┼──────────────────────────────────────────── …
```
> Resolve GHSA-qwcr-r2fm-qrc7 and GHSA-9wv6-86v2-598j

- change/@itwin-oidc-signin-tool-3c9c072f-ae0a-4ffc-a7fc-06d6c9871fe3.json
- packages/oidc-signin-tool/src/SignInAutomation.ts
Removes 4 waitForLoadState('networkidle') calls in SignInAutomation.ts as outlined in issue https://github.com/iTwin/auth-clients/issues/262
I was unable to get integration tests running locally (token requests failed with invalid client Id), even with the same configs and @ben-polinsky's help. Opening a PR for now to try integration tests through the pipeline.
> Remove Discouraged 'networkidle' Calls

- change/@itwin-browser-authorization-3f00ac2a-a4ab-4726-920a-e86d734aa609.json
- packages/browser/README.md
- packages/browser/src/index.ts
Spotted during workshop.
Side note: words "sign in" are not consistently spelled in methods' names (e.g. sign**i**n in `handleSigninCallback` and sign**I**n in `signInRedirect`). Not worth doing major version for, however.
> Fix method name in README.md

- .github/workflows/ci.yaml
- .github/workflows/create-release.yaml
https://github.com/pnpm/action-setup?tab=readme-ov-file
https://github.com/pnpm/action-setup/issues/135
v2 has stopped working due to actions no longer supporting node 16
> Update pnpm install action

- .vscode/settings.json
- change/@itwin-browser-authorization-cc3b2112-dbce-491a-96ac-6796f9258e4c.json
- change/@itwin-electron-authorization-d50363a6-f07e-422d-86b9-3f841e25f227.json
- packages/browser/README.md
- packages/browser/package.json
- packages/browser/playwright.config.ts
- packages/browser/src/integration-tests/helpers/TestHelper.ts
- packages/browser/vite.config.mts
- packages/electron/src/integration-test/integration.test.ts
- pnpm-lock.yaml
- Replace parcel with vite
- Remove `networkidle` waits in electron integration tests
> [browser] Integration test app - replace parcel with vite

- change/@itwin-browser-authorization-a0dd50e8-40d0-4e8b-808b-0f6cac62e869.json
- change/@itwin-electron-authorization-a5ea5b36-ec29-4f98-b8cb-2974baf65f46.json
- change/@itwin-oidc-signin-tool-3ad2e62a-b045-43e0-bdf4-9245cd442ba9.json
- package.json
- packages/browser/package.json
- packages/electron/package.json
- packages/oidc-signin-tool/package.json
- pnpm-lock.yaml
Remove `crypto-broserify` to address https://github.com/advisories/GHSA-vjh7-7g9h-fjfh
Bump vite to address https://github.com/advisories/GHSA-vg6x-rcgg-rjx6
add an override to `path-to-regexp` until new version of `certa` with new `express` is cut
> Address GHSA-vjh7-7g9h-fjfh

- .github/workflows/ci.yaml
- .github/workflows/create-github-release.yaml
- .github/workflows/publish-packages.yaml
- package.json
From this [SO](https://stackoverflow.com/questions/75766122/whats-the-difference-between-node-auth-token-and-npm-auth-token#comment138206931_77539464) post, we can derive that we need to specify the `registry-url` when setting up node. That way, `NODE_AUTH_TOKEN` would be used and added to `.npmrc` during our CI runs.
Also, we have to re-add `actions/setup-node` to our yaml scripts, because `pnpm/action-setup` [does not replace it](https://github.com/pnpm/action-setup?tab=readme-ov-file#notes). Also bumped the setup-node actions in `ci.yaml` to use v4 alongside.
Dry Run success: https://github.com/iTwin/auth-clients/actions/runs/13378305641/job/37362067098
> Reintroduce actions/setup-node and make sure registry-url is provided for npm publish authentication

- change/@itwin-electron-authorization-7f7c86fe-7b62-4e7d-848f-2d36792f35c6.json
- packages/electron/src/main/Client.ts
In the case of a connection client authentication workflow, we get the code from the connection client directly instead of a loop back webserver. So ,I need to expose a few methods so that I can override the signin method.
> Exposed a few methods to derived class to support other client

- change/@itwin-service-authorization-25a3c167-db19-4a67-97fd-77e7a9d5d396.json
- packages/service/package.json
- pnpm-lock.yaml
Because of missing peer dependency, users may see:
```
 WARN  Issues with peer dependencies found
...
└─┬ @itwin/service-authorization 1.2.2
└─┬ @itwin/core-common 4.2.1
└── ✕ missing peer @itwin/core-geometry@^4.2.1
Peer dependencies that should be installed:
@itwin/core-geometry@^4.2.1
```
> Add missing '@itwin/core-geometry' dependency to service package

- change/@itwin-browser-authorization-88706579-3cbe-4a92-bb43-cabef3097af0.json
- change/@itwin-electron-authorization-65bc18f2-c087-4733-a14c-d7724c8d29b8.json
- packages/browser/package.json
- packages/electron/package.json
- packages/electron/src/test/MainAuthorizationClient.test.ts
- packages/electron/tsconfig.json
- pnpm-lock.yaml
- Drop support for core v3 & v4 from browser-auth and electron-auth.
- Drop support for electron version < 35.
- Bump oidc-client-ts to v3.
> [browser/electron] drop core v3,v4 and electron < 35
